name: anilist_graphql
description: "A new Flutter project."
publish_to: 'none' 

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  graphql: ^5.1.3
  flutter_bloc:
  graphql_flutter_bloc: ^1.0.0
  artemis:
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  build_runner:
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

